import type { SimulationState, ModelTime } from "./enums.js";
import type { ErrorDetails } from "./exceptions.js";
import type { NodeConfiguration, NodePatch, NodeOperations } from "./objects/nodes.js";
import type { LinkConfiguration, LinkPatch, LinkOperations } from "./objects/links.js";
import type { SubcatchmentConfiguration, SubcatchmentPatch, SubcatchmentOperations } from "./objects/subcatchments.js";
import type { ModelOptions, ModelOptionsPatch, OptionsOperations } from "./objects/options.js";
import type { DefinitionOperations } from "./objects/definitions.js";
import type { AmmOperations } from "./objects/amm.js";
import type { RtkOperations } from "./objects/rtk.js";
import type { LidOperations } from "./objects/lids.js";
import type { OutputOperations } from "./output.js";
import type { ScenarioOperations } from "./scenarios.js";
import type { NodeResults, LinkResults, NodeSnapshot, LinkSnapshot, SubcatchmentResults, SubcatchmentSnapshot, RainGageResults, SimulationStatistics } from "./snapshots.js";
import type { SimulationInfo, SimulationStatus, RunResults } from "./types.js";

type Operation<A extends unknown[], R> = { args: A; result: R };
export interface Operations extends NodeOperations, LinkOperations, SubcatchmentOperations, OptionsOperations, DefinitionOperations, AmmOperations, RtkOperations, LidOperations, OutputOperations, ScenarioOperations {
  open: Operation<[Uint8Array, Record<string, Uint8Array>, number], SimulationInfo>;
  state: Operation<[], SimulationState>;
  info: Operation<[], SimulationInfo>;
  status: Operation<[], SimulationStatus>;
  start: Operation<[boolean], void>;
  step: Operation<[], ModelTime | null>;
  stride: Operation<[number, boolean], ModelTime | null>;
  node: Operation<[string], NodeResults>;
  link: Operation<[string], LinkResults>;
  nodes: Operation<[readonly string[] | undefined], NodeSnapshot>;
  links: Operation<[readonly string[] | undefined], LinkSnapshot>;
  subcatchment: Operation<[string], SubcatchmentResults>;
  subcatchments: Operation<[readonly string[] | undefined], SubcatchmentSnapshot>;
  rainGage: Operation<[string], RainGageResults>;
  nodeConfiguration: Operation<[string], NodeConfiguration>;
  linkConfiguration: Operation<[string], LinkConfiguration>;
  subcatchmentConfiguration: Operation<[string], SubcatchmentConfiguration>;
  configureNode: Operation<[string, NodePatch], void>;
  configureLink: Operation<[string, LinkPatch], void>;
  configureSubcatchment: Operation<[string, SubcatchmentPatch], void>;
  setNodeExternalInflow: Operation<[string, number], void>;
  setLinkTargetSetting: Operation<[string, number], void>;
  setOutfallStage: Operation<[string, number], void>;
  setRainGagePrecipitation: Operation<[string, number], void>;
  setRainGageRainfallOverride: Operation<[string, number | null], void>;
  options: Operation<[], ModelOptions>;
  configureOptions: Operation<[ModelOptionsPatch], void>;
  statistics: Operation<[], SimulationStatistics>;
  finish: Operation<[], RunResults>;
  run: Operation<[boolean], RunResults>;
  end: Operation<[], void>;
  finalizeReport: Operation<[], void>;
  report: Operation<[], void>;
  resetSolver: Operation<[], void>;
  sleepWorkers: Operation<[], void>;
  readFile: Operation<[string], Uint8Array>;
  close: Operation<[], void>;
}
export type Method = keyof Operations;
export type Args<K extends Method> = Operations[K]["args"];
export type Result<K extends Method> = Operations[K]["result"];
export type Call = <K extends Method>(method: K, ...args: Args<K>) => Promise<Result<K>>;
export type Request = { [K in Method]: { id: number; method: K; args: Args<K> } }[Method];
export type Response = { id: number; ok: true; result: unknown } |
  { id: number; ok: false; error: ErrorDetails; fatal: boolean };
