from collections.abc import Iterable, Mapping
from datetime import datetime, timedelta
from os import PathLike
from typing import Final, Literal, Never, Self, TypedDict, final

class _NativeMetadata(TypedDict):
    solver_release: int
    run_status: int | None
    flow_units: int
    unit_system: Literal["US", "SI"] | None
    report_schedule_origin: float
    report_step_seconds: int
    period_count: int
    subcatchments: list[tuple[int, bytes, float]]
    nodes: list[tuple[int, bytes, int, float, float]]
    links: list[tuple[int, bytes, int, float, float, float, float]]
    pollutants: list[tuple[int, bytes, int]]
    subcatchment_schema: list[tuple[int, int | None]]
    node_schema: list[tuple[int, int | None]]
    link_schema: list[tuple[int, int | None]]
    system_schema: list[tuple[int, None]]

class _NativeBulkSeriesPayload(TypedDict):
    times: list[float]
    series: list[tuple[str, int, int, list[float]]]

class _NativeSimulationStatus(TypedDict):
    state: str
    is_open: bool
    is_started: bool
    configuration_dirty: bool
    save_results: bool
    current_time: tuple[int, int, int, int, int, int] | None
    elapsed_seconds: float
    duration_seconds: float
    percent_complete: float
    step_count: int
    report_period_count: int
    warning_count: int

class NativeOutputError(Exception):
    args: tuple[str, str]

def _bind_public_types() -> None: ...

@final
class NativeOutputReader:
    def __new__(cls, path: str | PathLike[str]) -> Self: ...
    def metadata(self) -> _NativeMetadata: ...
    def read_bulk_series(
        self,
        selections: list[tuple[str, int, int]],
        start: int,
        end: int,
    ) -> _NativeBulkSeriesPayload: ...
    def read_bulk_series_by_period(
        self,
        selections: list[tuple[str, int, int]],
        start: int,
        end: int,
    ) -> _NativeBulkSeriesPayload: ...
    def read_stored_dates(self, start: int, end: int) -> list[float]: ...

@final
class NodeSnapshot:
    def __new__(cls, _token: Never) -> Self: ...
    @property
    def object_ids(self) -> tuple[str, ...]: ...
    @property
    def depth(self) -> tuple[float, ...]: ...
    @property
    def head(self) -> tuple[float, ...]: ...
    @property
    def volume(self) -> tuple[float, ...]: ...
    @property
    def lateral_inflow(self) -> tuple[float, ...]: ...
    @property
    def total_inflow(self) -> tuple[float, ...]: ...
    @property
    def total_outflow(self) -> tuple[float, ...]: ...
    @property
    def losses(self) -> tuple[float, ...]: ...
    @property
    def flooding(self) -> tuple[float, ...]: ...
    @property
    def hydraulic_retention_time(self) -> tuple[timedelta | None, ...]: ...

@final
class SubcatchmentSnapshot:
    def __new__(cls, _token: Never) -> Self: ...
    @property
    def object_ids(self) -> tuple[str, ...]: ...
    @property
    def rainfall(self) -> tuple[float, ...]: ...
    @property
    def evaporation(self) -> tuple[float, ...]: ...
    @property
    def infiltration(self) -> tuple[float, ...]: ...
    @property
    def runon(self) -> tuple[float, ...]: ...
    @property
    def runoff(self) -> tuple[float, ...]: ...
    @property
    def snow_depth(self) -> tuple[float, ...]: ...

@final
class LinkSnapshot:
    def __new__(cls, _token: Never) -> Self: ...
    @property
    def object_ids(self) -> tuple[str, ...]: ...
    @property
    def setting(self) -> tuple[float, ...]: ...
    @property
    def target_setting(self) -> tuple[float, ...]: ...
    @property
    def time_open(self) -> tuple[timedelta, ...]: ...
    @property
    def time_closed(self) -> tuple[timedelta, ...]: ...
    @property
    def flow(self) -> tuple[float, ...]: ...
    @property
    def depth(self) -> tuple[float, ...]: ...
    @property
    def velocity(self) -> tuple[float, ...]: ...
    @property
    def top_width(self) -> tuple[float | None, ...]: ...
    @property
    def volume(self) -> tuple[float, ...]: ...
    @property
    def capacity(self) -> tuple[float, ...]: ...
    @property
    def upstream_surface_area(self) -> tuple[float, ...]: ...
    @property
    def downstream_surface_area(self) -> tuple[float, ...]: ...
    @property
    def froude_number(self) -> tuple[float, ...]: ...

@final
class SubcatchmentQualitySnapshot:
    def __new__(cls, _token: Never) -> Self: ...
    @property
    def object_ids(self) -> tuple[str, ...]: ...
    @property
    def pollutant_ids(self) -> tuple[str, ...]: ...
    @property
    def runoff_concentrations(self) -> tuple[tuple[float, ...], ...]: ...
    @property
    def ponded_concentrations(self) -> tuple[tuple[float, ...], ...]: ...
    @property
    def buildup_loads(self) -> tuple[tuple[float, ...], ...]: ...
    @property
    def total_washoff_loads(self) -> tuple[tuple[float, ...], ...]: ...

@final
class NodeQualitySnapshot:
    def __new__(cls, _token: Never) -> Self: ...
    @property
    def object_ids(self) -> tuple[str, ...]: ...
    @property
    def pollutant_ids(self) -> tuple[str, ...]: ...
    @property
    def concentrations(self) -> tuple[tuple[float, ...], ...]: ...
    @property
    def inflow_concentrations(self) -> tuple[tuple[float, ...], ...]: ...
    @property
    def reactor_concentrations(self) -> tuple[tuple[float, ...], ...]: ...

@final
class LinkQualitySnapshot:
    def __new__(cls, _token: Never) -> Self: ...
    @property
    def object_ids(self) -> tuple[str, ...]: ...
    @property
    def pollutant_ids(self) -> tuple[str, ...]: ...
    @property
    def concentrations(self) -> tuple[tuple[float, ...], ...]: ...
    @property
    def reactor_concentrations(self) -> tuple[tuple[float, ...], ...]: ...
    @property
    def total_loads(self) -> tuple[tuple[float, ...], ...]: ...

@final
class NodeStatistics:
    def __new__(cls, _token: Never) -> Self: ...
    @property
    def average_depth(self) -> float: ...
    @property
    def maximum_depth(self) -> float: ...
    @property
    def maximum_depth_time(self) -> datetime: ...
    @property
    def maximum_reported_depth(self) -> float: ...
    @property
    def flooded_volume(self) -> float: ...
    @property
    def time_flooded(self) -> timedelta: ...
    @property
    def time_surcharged(self) -> timedelta: ...
    @property
    def time_courant_critical(self) -> timedelta: ...
    @property
    def total_lateral_inflow(self) -> float: ...
    @property
    def maximum_lateral_inflow(self) -> float: ...
    @property
    def maximum_inflow(self) -> float: ...
    @property
    def maximum_overflow(self) -> float: ...
    @property
    def maximum_ponded_volume(self) -> float: ...
    @property
    def nonconverged_count(self) -> int: ...
    @property
    def maximum_inflow_time(self) -> datetime: ...
    @property
    def maximum_overflow_time(self) -> datetime: ...

@final
class LidUnitSnapshot:
    def __new__(cls, _token: Never) -> Self: ...
    @property
    def inflow(self) -> float: ...
    @property
    def evaporation(self) -> float: ...
    @property
    def infiltration(self) -> float: ...
    @property
    def surface_outflow(self) -> float: ...
    @property
    def drain_outflow(self) -> float: ...
    @property
    def initial_volume(self) -> float: ...
    @property
    def final_volume(self) -> float: ...
    @property
    def surface_depth(self) -> float: ...
    @property
    def pavement_depth(self) -> float: ...
    @property
    def storage_depth(self) -> float: ...
    @property
    def soil_moisture(self) -> float: ...
    @property
    def dry_time(self) -> timedelta: ...
    @property
    def old_drain_flow(self) -> float: ...
    @property
    def new_drain_flow(self) -> float: ...
    @property
    def evaporation_rate(self) -> float: ...
    @property
    def maximum_native_infiltration_rate(self) -> float: ...
    @property
    def surface_inflow_rate(self) -> float: ...
    @property
    def surface_infiltration_rate(self) -> float: ...
    @property
    def surface_evaporation_rate(self) -> float: ...
    @property
    def surface_outflow_rate(self) -> float: ...
    @property
    def pavement_evaporation_rate(self) -> float: ...
    @property
    def pavement_percolation_rate(self) -> float: ...
    @property
    def soil_evaporation_rate(self) -> float: ...
    @property
    def soil_percolation_rate(self) -> float: ...
    @property
    def storage_inflow_rate(self) -> float: ...
    @property
    def storage_exfiltration_rate(self) -> float: ...
    @property
    def storage_evaporation_rate(self) -> float: ...
    @property
    def storage_drain_rate(self) -> float: ...
    @property
    def surface_flux_rate(self) -> float: ...
    @property
    def soil_flux_rate(self) -> float: ...
    @property
    def storage_flux_rate(self) -> float: ...
    @property
    def pavement_flux_rate(self) -> float: ...

@final
class StorageStatistics:
    def __new__(cls, _token: Never) -> Self: ...
    @property
    def initial_volume(self) -> float: ...
    @property
    def average_volume(self) -> float: ...
    @property
    def maximum_volume(self) -> float: ...
    @property
    def maximum_inflow(self) -> float: ...
    @property
    def evaporation_losses(self) -> float: ...
    @property
    def exfiltration_losses(self) -> float: ...
    @property
    def maximum_volume_time(self) -> datetime: ...

@final
class OutfallStatistics:
    def __new__(cls, _token: Never) -> Self: ...
    @property
    def average_flow(self) -> float: ...
    @property
    def maximum_flow(self) -> float: ...
    @property
    def pollutant_loads(self) -> Mapping[str, float]: ...
    @property
    def period_count(self) -> int: ...

@final
class LinkStatistics:
    def __new__(cls, _token: Never) -> Self: ...
    @property
    def maximum_flow(self) -> float: ...
    @property
    def maximum_flow_time(self) -> datetime: ...
    @property
    def maximum_velocity(self) -> float: ...
    @property
    def maximum_depth(self) -> float: ...
    @property
    def maximum_street_fill_fraction(self) -> float | None: ...
    @property
    def time_normal_flow(self) -> timedelta: ...
    @property
    def time_inlet_control(self) -> timedelta: ...
    @property
    def time_surcharged(self) -> timedelta: ...
    @property
    def time_full_upstream(self) -> timedelta: ...
    @property
    def time_full_downstream(self) -> timedelta: ...
    @property
    def time_full_flow(self) -> timedelta: ...
    @property
    def time_capacity_limited(self) -> timedelta: ...
    @property
    def time_in_flow_class(self) -> tuple[timedelta, ...]: ...
    @property
    def time_courant_critical(self) -> timedelta: ...
    @property
    def flow_turns(self) -> int: ...
    @property
    def flow_turn_sign(self) -> Literal[-1, 0, 1]: ...

@final
class PumpStatistics:
    def __new__(cls, _token: Never) -> Self: ...
    @property
    def time_utilized(self) -> timedelta: ...
    @property
    def minimum_flow(self) -> float: ...
    @property
    def average_flow(self) -> float: ...
    @property
    def maximum_flow(self) -> float: ...
    @property
    def pumped_volume(self) -> float: ...
    @property
    def energy_consumed(self) -> float: ...
    @property
    def off_curve_low(self) -> timedelta: ...
    @property
    def off_curve_high(self) -> timedelta: ...
    @property
    def startup_count(self) -> int: ...
    @property
    def period_count(self) -> int: ...

@final
class SubcatchmentStatistics:
    def __new__(cls, _token: Never) -> Self: ...
    @property
    def precipitation(self) -> float: ...
    @property
    def runon_volume(self) -> float: ...
    @property
    def evaporation_volume(self) -> float: ...
    @property
    def infiltration_volume(self) -> float: ...
    @property
    def runoff_volume(self) -> float: ...
    @property
    def maximum_runoff(self) -> float: ...
    @property
    def impervious_runoff_volume(self) -> float: ...
    @property
    def pervious_runoff_volume(self) -> float: ...

@final
class NodeStatisticsSnapshot:
    def __new__(cls, _token: Never) -> Self: ...
    @property
    def object_ids(self) -> tuple[str, ...]: ...
    @property
    def average_depth(self) -> tuple[float, ...]: ...
    @property
    def maximum_depth(self) -> tuple[float, ...]: ...
    @property
    def maximum_depth_time(self) -> tuple[datetime, ...]: ...
    @property
    def maximum_reported_depth(self) -> tuple[float, ...]: ...
    @property
    def flooded_volume(self) -> tuple[float, ...]: ...
    @property
    def time_flooded(self) -> tuple[timedelta, ...]: ...
    @property
    def time_surcharged(self) -> tuple[timedelta, ...]: ...
    @property
    def time_courant_critical(self) -> tuple[timedelta, ...]: ...
    @property
    def total_lateral_inflow(self) -> tuple[float, ...]: ...
    @property
    def maximum_lateral_inflow(self) -> tuple[float, ...]: ...
    @property
    def maximum_inflow(self) -> tuple[float, ...]: ...
    @property
    def maximum_overflow(self) -> tuple[float, ...]: ...
    @property
    def maximum_ponded_volume(self) -> tuple[float, ...]: ...
    @property
    def nonconverged_count(self) -> tuple[int, ...]: ...
    @property
    def maximum_inflow_time(self) -> tuple[datetime, ...]: ...
    @property
    def maximum_overflow_time(self) -> tuple[datetime, ...]: ...

@final
class LinkStatisticsSnapshot:
    def __new__(cls, _token: Never) -> Self: ...
    @property
    def object_ids(self) -> tuple[str, ...]: ...
    @property
    def maximum_flow(self) -> tuple[float, ...]: ...
    @property
    def maximum_flow_time(self) -> tuple[datetime, ...]: ...
    @property
    def maximum_velocity(self) -> tuple[float, ...]: ...
    @property
    def maximum_depth(self) -> tuple[float, ...]: ...
    @property
    def maximum_street_fill_fraction(self) -> tuple[float | None, ...]: ...
    @property
    def time_normal_flow(self) -> tuple[timedelta, ...]: ...
    @property
    def time_inlet_control(self) -> tuple[timedelta, ...]: ...
    @property
    def time_surcharged(self) -> tuple[timedelta, ...]: ...
    @property
    def time_full_upstream(self) -> tuple[timedelta, ...]: ...
    @property
    def time_full_downstream(self) -> tuple[timedelta, ...]: ...
    @property
    def time_full_flow(self) -> tuple[timedelta, ...]: ...
    @property
    def time_capacity_limited(self) -> tuple[timedelta, ...]: ...
    @property
    def time_in_flow_class(self) -> tuple[tuple[timedelta, ...], ...]: ...
    @property
    def time_courant_critical(self) -> tuple[timedelta, ...]: ...
    @property
    def flow_turns(self) -> tuple[int, ...]: ...
    @property
    def flow_turn_sign(self) -> tuple[Literal[-1, 0, 1], ...]: ...

@final
class SubcatchmentLidSnapshot:
    def __new__(cls, _token: Never) -> Self: ...
    @property
    def pervious_area(self) -> float: ...
    @property
    def flow_to_pervious_area(self) -> float: ...
    @property
    def old_drain_flow(self) -> float: ...
    @property
    def new_drain_flow(self) -> float: ...

@final
class SubcatchmentStatisticsSnapshot:
    def __new__(cls, _token: Never) -> Self: ...
    @property
    def object_ids(self) -> tuple[str, ...]: ...
    @property
    def precipitation(self) -> tuple[float, ...]: ...
    @property
    def runon_volume(self) -> tuple[float, ...]: ...
    @property
    def evaporation_volume(self) -> tuple[float, ...]: ...
    @property
    def infiltration_volume(self) -> tuple[float, ...]: ...
    @property
    def runoff_volume(self) -> tuple[float, ...]: ...
    @property
    def maximum_runoff(self) -> tuple[float, ...]: ...
    @property
    def impervious_runoff_volume(self) -> tuple[float, ...]: ...
    @property
    def pervious_runoff_volume(self) -> tuple[float, ...]: ...

@final
class RoutingDiagnostics:
    def __new__(cls, _token: Never) -> Self: ...
    @property
    def average_time_step(self) -> timedelta: ...
    @property
    def minimum_time_step(self) -> timedelta: ...
    @property
    def maximum_time_step(self) -> timedelta: ...
    @property
    def step_count(self) -> int: ...
    @property
    def nonconverged_step_count(self) -> int: ...
    @property
    def nonconverged_step_percentage(self) -> float: ...
    @property
    def average_iterations(self) -> float: ...

@final
class RoutingTotals:
    def __new__(cls, _token: Never) -> Self: ...
    @property
    def dry_weather_inflow(self) -> float: ...
    @property
    def wet_weather_inflow(self) -> float: ...
    @property
    def groundwater_inflow(self) -> float: ...
    @property
    def rdii_inflow(self) -> float: ...
    @property
    def external_inflow(self) -> float: ...
    @property
    def flooding(self) -> float: ...
    @property
    def outflow(self) -> float: ...
    @property
    def evaporation_loss(self) -> float: ...
    @property
    def seepage_loss(self) -> float: ...
    @property
    def reaction_loss(self) -> float: ...
    @property
    def initial_storage(self) -> float: ...
    @property
    def final_storage(self) -> float: ...
    @property
    def continuity_error(self) -> float: ...

@final
class RunoffTotals:
    def __new__(cls, _token: Never) -> Self: ...
    @property
    def rainfall(self) -> float: ...
    @property
    def evaporation_loss(self) -> float: ...
    @property
    def infiltration_loss(self) -> float: ...
    @property
    def runoff(self) -> float: ...
    @property
    def lid_drain_flow(self) -> float: ...
    @property
    def outfall_runon(self) -> float: ...
    @property
    def initial_surface_storage(self) -> float: ...
    @property
    def final_surface_storage(self) -> float: ...
    @property
    def initial_snow_cover(self) -> float: ...
    @property
    def final_snow_cover(self) -> float: ...
    @property
    def snow_removed(self) -> float: ...
    @property
    def continuity_error(self) -> float: ...

@final
class QualityBalance:
    def __new__(cls, _token: Never) -> Self: ...
    @property
    def continuity_error(self) -> float: ...
    @property
    def seepage_loss(self) -> float: ...

@final
class SimulationStatistics:
    def __new__(cls, _token: Never) -> Self: ...
    @property
    def routing_totals(self) -> RoutingTotals: ...
    @property
    def runoff_totals(self) -> RunoffTotals: ...
    @property
    def groundwater_continuity_error(self) -> float: ...
    @property
    def quality_continuity_error(self) -> float: ...
    @property
    def routing_diagnostics(self) -> RoutingDiagnostics: ...
    @property
    def quality_balances(self) -> Mapping[str, QualityBalance]: ...

_SnapshotSelection = str | int | Iterable[str | int] | None
_PathInput = str | PathLike[str]

@final
class NativeSimulation:
    def __new__(
        cls,
        input: _PathInput,
        report: _PathInput | None = ...,
        output: _PathInput | None = ...,
    ) -> Self: ...
    def open(
        self,
        input: _PathInput,
        report: _PathInput | None = ...,
        output: _PathInput | None = ...,
    ) -> None: ...
    @property
    def input_path(self) -> str: ...
    @property
    def report_path(self) -> str: ...
    @property
    def output_path(self) -> str | None: ...
    @property
    def state(self) -> str: ...
    def status(self) -> _NativeSimulationStatus: ...
    @property
    def is_open(self) -> bool: ...
    @property
    def generation(self) -> int: ...
    def collection_view(
        self, facade: object, generation: int, family: int, key: object
    ) -> object: ...
    def collection_view_at(
        self, facade: object, generation: int, family: int, position: object
    ) -> object: ...
    def collection_contains(self, generation: int, family: int, key: object) -> bool: ...
    def collection_count(self, generation: int, family: int) -> int: ...
    def collection_ids(self, generation: int, family: int) -> list[str]: ...
    def validate_identity(
        self,
        generation: int,
        family: int,
        index: int,
        id: str,
        subtype: str,
    ) -> None: ...
    def update_aquifer(
        self,
        generation: int,
        index: int,
        id: str,
        subtype: str,
        changes: dict[str, object],
    ) -> None: ...
    def amm_model_configuration(
        self,
        facade: object,
        generation: int,
        index: int,
        id: str,
        subtype: str,
    ) -> tuple[object, float, float, tuple[tuple[object, ...], ...]]: ...
    def update_amm_model(
        self,
        generation: int,
        index: int,
        id: str,
        subtype: str,
        changes: dict[str, object],
    ) -> None: ...
    def amm_assignments(
        self, facade: object, generation: int
    ) -> tuple[tuple[object, object, float], ...]: ...
    def replace_amm_assignments(
        self, generation: int, assignments: tuple[tuple[object, object, float], ...]
    ) -> None: ...
    def unit_hydrograph_configuration(
        self,
        facade: object,
        generation: int,
        index: int,
        id: str,
        subtype: str,
    ) -> tuple[
        object,
        tuple[tuple[tuple[float, float, float, float, float, float], ...], ...],
    ]: ...
    def update_unit_hydrograph(
        self,
        generation: int,
        index: int,
        id: str,
        subtype: str,
        changes: dict[str, object],
    ) -> None: ...
    def rdii_assignments(
        self, facade: object, generation: int
    ) -> tuple[tuple[object, object, float], ...]: ...
    def replace_rdii_assignments(
        self, generation: int, assignments: tuple[tuple[object, object, float], ...]
    ) -> None: ...
    def snowmelt_configuration_value(
        self, facade: object, generation: int, index: int, id: str, subtype: str, field: str
    ) -> object: ...
    def snowmelt_surface_configuration_value(
        self,
        generation: int,
        index: int,
        id: str,
        subtype: str,
        surface: str,
        field: str,
    ) -> float: ...
    def update_snowmelt(
        self,
        generation: int,
        index: int,
        id: str,
        subtype: str,
        surface: str | None,
        changes: dict[str, object],
    ) -> None: ...
    def rain_gage_precipitation_value(
        self, generation: int, index: int, id: str, subtype: str, field: str
    ) -> float: ...
    def rain_gage_external_precipitation_rate(
        self, generation: int, index: int, id: str, subtype: str
    ) -> float | None: ...
    def rain_gage_rainfall_override(
        self, generation: int, index: int, id: str, subtype: str
    ) -> float | None: ...
    def use_rain_gage_external_precipitation(
        self,
        generation: int,
        index: int,
        id: str,
        subtype: str,
        value: object,
    ) -> None: ...
    def set_rain_gage_rainfall_override(
        self,
        generation: int,
        index: int,
        id: str,
        subtype: str,
        value: object,
    ) -> None: ...
    def subcatchment_precipitation_scale_factor(
        self, generation: int, index: int, id: str, subtype: str, field: str
    ) -> float: ...
    def subcatchment_configuration_value(
        self, facade: object, generation: int, index: int, id: str, subtype: str, field: str
    ) -> object: ...
    def update_subcatchment(
        self,
        generation: int,
        index: int,
        id: str,
        subtype: str,
        changes: dict[str, object],
    ) -> None: ...
    def subcatchment_infiltration_value(
        self,
        generation: int,
        index: int,
        id: str,
        subtype: str,
        expected_kind: str | None,
        field: str,
    ) -> object: ...
    def subcatchment_groundwater_value(
        self, facade: object, generation: int, index: int, id: str, subtype: str, field: str
    ) -> object: ...
    def subcatchment_snowpack(
        self, facade: object, generation: int, index: int, id: str, subtype: str
    ) -> object | None: ...
    def subcatchment_named_settings_mapping(
        self, generation: int, index: int, id: str, subtype: str, mapping: str
    ) -> list[tuple[str, float]]: ...
    def subcatchment_named_setting_value(
        self,
        generation: int,
        index: int,
        id: str,
        subtype: str,
        mapping: str,
        key: object,
    ) -> float: ...
    def update_subcatchment_named_settings(
        self,
        generation: int,
        index: int,
        id: str,
        subtype: str,
        mapping: str,
        replace: bool,
        values: object,
    ) -> None: ...
    def update_subcatchment_infiltration(
        self,
        generation: int,
        index: int,
        id: str,
        subtype: str,
        expected_kind: str,
        changes: dict[str, object],
    ) -> None: ...
    def update_subcatchment_groundwater(
        self,
        generation: int,
        index: int,
        id: str,
        subtype: str,
        changes: dict[str, object],
    ) -> None: ...
    def aquifer_configuration_value(
        self, facade: object, generation: int, index: int, id: str, subtype: str, field: str
    ) -> object: ...
    def subcatchment_external_forcing_value(
        self, generation: int, index: int, id: str, subtype: str, field: str
    ) -> float: ...
    def subcatchment_result(
        self, generation: int, index: int, id: str, subtype: str, field: str
    ) -> float: ...
    def subcatchment_snapshot(
        self, generation: int, ids: _SnapshotSelection
    ) -> SubcatchmentSnapshot: ...
    def subcatchment_quality_mapping(
        self, generation: int, index: int, id: str, subtype: str, field: str
    ) -> tuple[list[str], list[float]]: ...
    def subcatchment_external_pollutant_buildup_increment(
        self, generation: int, index: int, id: str, subtype: str
    ) -> tuple[list[str], list[float]]: ...
    def subcatchment_quality_snapshot(
        self, generation: int, ids: _SnapshotSelection
    ) -> SubcatchmentQualitySnapshot: ...
    def subcatchment_external_pollutant_buildup_increment_value(
        self,
        generation: int,
        index: int,
        id: str,
        subtype: str,
        pollutant_id: object,
    ) -> float: ...
    def update_subcatchment_external_pollutant_buildup_increment(
        self,
        generation: int,
        index: int,
        id: str,
        subtype: str,
        replace: bool,
        args: tuple[object, ...],
        kwargs: dict[str, float],
    ) -> None: ...
    def subcatchment_lid_snapshot(
        self, generation: int, index: int, id: str, subtype: str
    ) -> SubcatchmentLidSnapshot: ...
    def set_subcatchment_precipitation_scale_factors(
        self,
        generation: int,
        index: int,
        id: str,
        subtype: str,
        rainfall: object,
        snowfall: object,
    ) -> None: ...
    def set_subcatchment_external_rainfall(
        self,
        generation: int,
        index: int,
        id: str,
        subtype: str,
        value: object,
    ) -> None: ...
    def set_subcatchment_external_snowfall(
        self,
        generation: int,
        index: int,
        id: str,
        subtype: str,
        value: object,
    ) -> None: ...
    def node_configuration_value(
        self, facade: object, generation: int, index: int, id: str, subtype: str, field: str
    ) -> object: ...
    def node_external_inflow(self, generation: int, index: int, id: str, subtype: str) -> float: ...
    def node_result(
        self, generation: int, index: int, id: str, subtype: str, field: str
    ) -> float: ...
    def node_snapshot(self, generation: int, ids: _SnapshotSelection) -> NodeSnapshot: ...
    def node_quality_mapping(
        self, generation: int, index: int, id: str, subtype: str, field: str
    ) -> tuple[list[str], list[float]]: ...
    def node_external_pollutant_mass_flux(
        self, generation: int, index: int, id: str, subtype: str
    ) -> tuple[list[str], list[float]]: ...
    def node_quality_snapshot(
        self, generation: int, ids: _SnapshotSelection
    ) -> NodeQualitySnapshot: ...
    def override_node_pollutant_concentrations(
        self,
        generation: int,
        index: int,
        id: str,
        subtype: str,
        values: object,
    ) -> None: ...
    def node_external_pollutant_mass_flux_value(
        self,
        generation: int,
        index: int,
        id: str,
        subtype: str,
        pollutant_id: object,
    ) -> float: ...
    def update_node_external_pollutant_mass_flux(
        self,
        generation: int,
        index: int,
        id: str,
        subtype: str,
        replace: bool,
        args: tuple[object, ...],
        kwargs: dict[str, float],
    ) -> None: ...
    def outfall_fixed_stage(
        self, generation: int, index: int, id: str, subtype: str
    ) -> float | None: ...
    def node_total_inflow_volume(
        self, generation: int, index: int, id: str, subtype: str
    ) -> float: ...
    def update_node_settings(
        self,
        generation: int,
        index: int,
        id: str,
        subtype: str,
        changes: dict[str, object],
    ) -> None: ...
    def set_node_external_inflow(
        self, generation: int, index: int, id: str, subtype: str, value: object
    ) -> None: ...
    def set_outfall_fixed_stage(
        self, generation: int, index: int, id: str, subtype: str, value: object
    ) -> None: ...
    def link_configuration_value(
        self, facade: object, generation: int, index: int, id: str, subtype: str, field: str
    ) -> object: ...
    def update_link_settings(
        self,
        generation: int,
        index: int,
        id: str,
        subtype: str,
        changes: dict[str, object],
    ) -> None: ...
    def use_pump_curve(
        self, generation: int, index: int, id: str, subtype: str, curve: object
    ) -> None: ...
    def use_ideal_pump(self, generation: int, index: int, id: str, subtype: str) -> None: ...
    def link_result(
        self, generation: int, index: int, id: str, subtype: str, field: str
    ) -> float | None: ...
    def link_quality_mapping(
        self, generation: int, index: int, id: str, subtype: str, field: str
    ) -> tuple[list[str], list[float]]: ...
    def link_external_pollutant_mass_flux(
        self, generation: int, index: int, id: str, subtype: str
    ) -> tuple[list[str], list[float]]: ...
    def link_inlet(
        self, facade: object, generation: int, index: int, id: str, subtype: str
    ) -> object | None: ...
    def inlet_configuration_value(
        self,
        facade: object,
        generation: int,
        link_index: int,
        link_id: str,
        link_subtype: str,
        design_index: int,
        design_id: str,
        field: str,
    ) -> object: ...
    def inlet_persistent_configuration_value(
        self,
        facade: object,
        generation: int,
        link_index: int,
        link_id: str,
        link_subtype: str,
        design_index: int,
        design_id: str,
        field: str,
    ) -> object: ...
    def inlet_result(
        self,
        generation: int,
        link_index: int,
        link_id: str,
        link_subtype: str,
        design_index: int,
        design_id: str,
        field: str,
    ) -> float: ...
    def update_inlet(
        self,
        generation: int,
        link_index: int,
        link_id: str,
        link_subtype: str,
        design_index: int,
        design_id: str,
        changes: dict[str, object],
    ) -> None: ...
    def link_snapshot(self, generation: int, ids: _SnapshotSelection) -> LinkSnapshot: ...
    def link_quality_snapshot(
        self, generation: int, ids: _SnapshotSelection
    ) -> LinkQualitySnapshot: ...
    def override_link_pollutant_concentrations(
        self,
        generation: int,
        index: int,
        id: str,
        subtype: str,
        values: object,
    ) -> None: ...
    def link_external_pollutant_mass_flux_value(
        self,
        generation: int,
        index: int,
        id: str,
        subtype: str,
        pollutant_id: object,
    ) -> float: ...
    def update_link_external_pollutant_mass_flux(
        self,
        generation: int,
        index: int,
        id: str,
        subtype: str,
        replace: bool,
        args: tuple[object, ...],
        kwargs: dict[str, float],
    ) -> None: ...
    def set_link_flow_limit(
        self,
        generation: int,
        index: int,
        id: str,
        subtype: str,
        value: object,
    ) -> None: ...
    def set_link_target_setting(
        self,
        generation: int,
        index: int,
        id: str,
        subtype: str,
        value: object,
    ) -> None: ...
    def lid_unit_count(
        self,
        generation: int,
        subcatchment_index: int,
        subcatchment_id: str,
        subcatchment_subtype: str,
    ) -> int: ...
    def lid_unit_value(
        self,
        facade: object,
        generation: int,
        subcatchment_index: int,
        subcatchment_id: str,
        subcatchment_subtype: str,
        unit_index: int,
        field: str,
    ) -> object: ...
    def lid_unit_snapshot(
        self,
        generation: int,
        subcatchment_index: int,
        subcatchment_id: str,
        subcatchment_subtype: str,
        unit_index: int,
    ) -> LidUnitSnapshot: ...
    def update_lid_unit(
        self,
        generation: int,
        subcatchment_index: int,
        subcatchment_id: str,
        subcatchment_subtype: str,
        unit_index: int,
        changes: dict[str, object],
    ) -> None: ...
    def lid_control_layer_exists(
        self,
        generation: int,
        index: int,
        id: str,
        subtype: str,
        layer: str,
    ) -> bool: ...
    def lid_control_value(
        self,
        facade: object,
        generation: int,
        index: int,
        id: str,
        subtype: str,
        layer: str,
        field: str,
    ) -> object: ...
    def update_lid_control_layer(
        self,
        generation: int,
        index: int,
        id: str,
        subtype: str,
        layer: str,
        changes: dict[str, object],
    ) -> None: ...
    @property
    def is_started(self) -> bool: ...
    @property
    def configuration_dirty(self) -> bool: ...
    @property
    def warning_count(self) -> int: ...
    @property
    def report_period_count(self) -> int: ...
    def simulation_time(self, field: str) -> tuple[int, int, int, int, int, int]: ...
    def current_time(self) -> tuple[int, int, int, int, int, int]: ...
    def elapsed_times(
        self,
    ) -> tuple[
        tuple[int, int, int, int, int, int],
        tuple[int, int, int, int, int, int],
    ]: ...
    def unit_label(self, field: str) -> str: ...
    def option_value(self, generation: int, field: str) -> object: ...
    def options_read(self, generation: int) -> dict[str, object]: ...
    @property
    def effective_threads(self) -> int: ...
    def maximum_routing_step(self, generation: int) -> float: ...
    def update_schedule(self, generation: int, changes: dict[str, object]) -> None: ...
    def update_options(self, generation: int, changes: dict[str, object]) -> None: ...
    def start(self, save_results: bool) -> None: ...
    def reset_solver(self) -> None: ...
    def sleep_workers(self) -> None: ...
    def use_hotstart(self, path: _PathInput | None = ...) -> None: ...
    def save_checkpoint(self, path: _PathInput) -> None: ...
    @staticmethod
    def resume(
        checkpoint: _PathInput, report: _PathInput, output: _PathInput
    ) -> NativeSimulation: ...
    def load_checkpoint_state(self, path: _PathInput) -> None: ...
    def fork(self, report: _PathInput, output: _PathInput) -> NativeSimulation: ...
    def save_hotstart(self, path: _PathInput) -> None: ...
    def step(self) -> tuple[int, int, int, int, int, int] | None: ...
    def stride(
        self, duration: timedelta | float, strict: bool
    ) -> tuple[int, int, int, int, int, int] | None: ...
    def step_advance(
        self, duration: timedelta | float | None, strict: bool
    ) -> None: ...
    def iterator_next(self) -> tuple[int, int, int, int, int, int] | None: ...
    def terminate(self) -> None: ...
    def execute(self, save_results: bool) -> None: ...
    def end(self) -> None: ...
    def report(self) -> None: ...
    def node_statistics(
        self, generation: int, index: int, id: str, subtype: str
    ) -> NodeStatistics: ...
    def storage_statistics(
        self, generation: int, index: int, id: str, subtype: str
    ) -> StorageStatistics: ...
    def outfall_statistics(
        self, generation: int, index: int, id: str, subtype: str
    ) -> OutfallStatistics: ...
    def link_statistics(
        self, generation: int, index: int, id: str, subtype: str
    ) -> LinkStatistics: ...
    def pump_statistics(
        self, generation: int, index: int, id: str, subtype: str
    ) -> PumpStatistics: ...
    def subcatchment_statistics(
        self, generation: int, index: int, id: str, subtype: str
    ) -> SubcatchmentStatistics: ...
    def node_statistics_snapshot(
        self, generation: int, ids: _SnapshotSelection
    ) -> NodeStatisticsSnapshot: ...
    def link_statistics_snapshot(
        self, generation: int, ids: _SnapshotSelection
    ) -> LinkStatisticsSnapshot: ...
    def subcatchment_statistics_snapshot(
        self, generation: int, ids: _SnapshotSelection
    ) -> SubcatchmentStatisticsSnapshot: ...
    def simulation_statistics(self, generation: int) -> SimulationStatistics: ...
    def close(self) -> None: ...

solver_version: Final[str]
solver_build_id: Final[str]
