"""Typed, generation-bound views over configured SWMM project objects.

All view instances retain the simulation and project generation that created them.
They validate that identity before accessing native state, so retained views cannot
silently address a subsequently reopened project.
"""

from ._amm import AmmAssignment, AmmBaseflowComponent, AmmModel, AmmStandardComponent
from ._base import _ObjectFamily
from ._collections import ObjectCollection, _new_collection
from ._definitions import (
    Aquifer,
    ControlRule,
    Curve,
    CustomShape,
    InletDesign,
    LandUse,
    Pollutant,
    RdiiAssignment,
    SnowmeltParameterSet,
    SnowmeltSurface,
    Street,
    TimePattern,
    TimeSeries,
    Transect,
    UnitHydrograph,
    UnitHydrographMonth,
    UnitHydrographResponse,
)
from ._lids import (
    LidControl,
    LidDrainageMatLayer,
    LidDrainLayer,
    LidPavementLayer,
    LidSoilLayer,
    LidStorageLayer,
    LidSurfaceLayer,
)
from ._links import (
    CircularCrossSection,
    Conduit,
    ConduitSettings,
    CustomCrossSection,
    FunctionalOutletRating,
    Inlet,
    InletSettings,
    IrregularCrossSection,
    Link,
    LinkCollection,
    LinkSettings,
    Orifice,
    OrificeSettings,
    Outlet,
    OutletSettings,
    Pump,
    PumpSettings,
    StandardCrossSection,
    StreetCrossSection,
    TabularOutletRating,
    Weir,
    WeirSettings,
)
from ._nodes import (
    Divider,
    DividerRule,
    DividerSettings,
    Junction,
    Node,
    NodeCollection,
    NodeSettings,
    Outfall,
    OutfallBoundary,
    OutfallSettings,
    StorageExfiltration,
    StorageNode,
    StorageSettings,
    StorageShape,
)
from ._options import SimulationOptions, _new_options
from ._subcatchments import (
    CurveNumberInfiltrationSettings,
    GreenAmptInfiltrationSettings,
    HortonInfiltrationSettings,
    LidUnit,
    LidUnitCollection,
    ModifiedGreenAmptInfiltrationSettings,
    ModifiedHortonInfiltrationSettings,
    RainGage,
    Subcatchment,
    SubcatchmentCollection,
    SubcatchmentGroundwater,
    SubcatchmentGroundwaterSettings,
    SubcatchmentInfiltration,
    SubcatchmentSettings,
)

__all__ = (
    "AmmAssignment",
    "AmmBaseflowComponent",
    "AmmModel",
    "AmmStandardComponent",
    "Aquifer",
    "CircularCrossSection",
    "CustomCrossSection",
    "IrregularCrossSection",
    "StandardCrossSection",
    "StreetCrossSection",
    "Conduit",
    "ConduitSettings",
    "ControlRule",
    "CurveNumberInfiltrationSettings",
    "Curve",
    "CustomShape",
    "Divider",
    "DividerRule",
    "DividerSettings",
    "FunctionalOutletRating",
    "GreenAmptInfiltrationSettings",
    "HortonInfiltrationSettings",
    "Inlet",
    "InletDesign",
    "InletSettings",
    "Junction",
    "LandUse",
    "LidControl",
    "LidDrainLayer",
    "LidDrainageMatLayer",
    "LidPavementLayer",
    "LidSoilLayer",
    "LidStorageLayer",
    "LidSurfaceLayer",
    "LidUnit",
    "LidUnitCollection",
    "Link",
    "LinkSettings",
    "ModifiedGreenAmptInfiltrationSettings",
    "ModifiedHortonInfiltrationSettings",
    "LinkCollection",
    "Node",
    "NodeCollection",
    "NodeSettings",
    "ObjectCollection",
    "Orifice",
    "OrificeSettings",
    "Outfall",
    "OutfallBoundary",
    "OutfallSettings",
    "Outlet",
    "OutletSettings",
    "Pollutant",
    "Pump",
    "PumpSettings",
    "RdiiAssignment",
    "RainGage",
    "SimulationOptions",
    "SnowmeltParameterSet",
    "SnowmeltSurface",
    "StorageExfiltration",
    "StorageNode",
    "StorageSettings",
    "StorageShape",
    "Street",
    "Subcatchment",
    "SubcatchmentCollection",
    "SubcatchmentGroundwater",
    "SubcatchmentGroundwaterSettings",
    "SubcatchmentInfiltration",
    "SubcatchmentSettings",
    "TabularOutletRating",
    "TimePattern",
    "TimeSeries",
    "Transect",
    "UnitHydrograph",
    "UnitHydrographMonth",
    "UnitHydrographResponse",
    "Weir",
    "WeirSettings",
)

_name = ""
for _name in __all__:
    globals()[_name].__module__ = __name__
del _name
